spring:
  application.name: testcleaner
  datasource:
    url: jdbc:mysql://localhost:3306/test-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
